#ifndef SCONFIG_H
#define SCONFIG_H

#include <QtCore/qglobal.h>

#define SQUERY_VERSION_MAJOR 1
#define SQUERY_VERSION_MINOR 0
#define SQUERY_VERSION_PATCH 0

#define SQUERY_VERSION_CHECK QT_VERSION_CHECK
#define SQUERY_VERSION SQUERY_VERSION_CHECK(SQUERY_VERSION_MAJOR, SQUERY_VERSION_MINOR, SQUERY_VERSION_PATCH)

#define SQUERY_STATIC

#endif // SCONFIG
